static const char keyRegisterDialogString [] = 
{
  "<?xml version=\"1.0\" ?><!-- Generated with glade 3.18.3 --><int"
  "erface><requires lib=\"gtk+\" version=\"3.12\"/><object class=\""
  "GtkDialog\" id=\"dialogKeyRegister\"><property name=\"can_focus\""
  ">False</property><property name=\"type_hint\">dialog</property><"
  "signal handler=\"on_dialogKeyRegister_unrealize\" name=\"unreali"
  "ze\" swapped=\"no\"/><child internal-child=\"vbox\"><object clas"
  "s=\"GtkBox\" id=\"dialog-vbox1\"><property name=\"can_focus\">Fa"
  "lse</property><property name=\"orientation\">vertical</property>"
  "<property name=\"spacing\">2</property><signal handler=\"on_dial"
  "og_key_press_event\" name=\"key-press-event\" object=\"lblInfo\""
  " swapped=\"no\"/><child internal-child=\"action_area\"><object c"
  "lass=\"GtkButtonBox\" id=\"dialog-action_area1\"><property name="
  "\"can_focus\">False</property><property name=\"layout_style\">en"
  "d</property><child><object class=\"GtkButton\" id=\"btnCancel\">"
  "<property name=\"label\" translatable=\"yes\">Cancel</property><"
  "property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">True</property><property name=\"receives_default\">True</p"
  "roperty><signal handler=\"on_btnCancel_clicked\" name=\"clicked\""
  " object=\"dialogKeyRegister\" swapped=\"no\"/></object><packing>"
  "<property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">0</property></packin"
  "g></child><child><object class=\"GtkButton\" id=\"btnOk\"><prope"
  "rty name=\"label\" translatable=\"yes\">OK</property><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"receives_default\">True</property><s"
  "ignal handler=\"on_btnOk_clicked\" name=\"clicked\" object=\"lbl"
  "Info\" swapped=\"no\"/></object><packing><property name=\"expand"
  "\">True</property><property name=\"fill\">True</property><proper"
  "ty name=\"position\">1</property></packing></child></object><pac"
  "king><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">0</property><"
  "/packing></child><child><object class=\"GtkBox\" id=\"box1\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"orientation\">vertical</pro"
  "perty><child><object class=\"GtkLabel\" id=\"lblInfo\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"margin_top\">25</property><proper"
  "ty name=\"margin_bottom\">25</property><property name=\"label\" "
  "translatable=\"yes\">Press the keys...</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">0</property></pa"
  "cking></child></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">True</property><property name="
  "\"position\">1</property></packing></child></object></child></ob"
  "ject></interface>"
};
