static const char mainWindowString [] = 
{
  "<?xml version=\"1.0\" ?><!-- Generated with glade 3.18.3 --><int"
  "erface><requires lib=\"gtk+\" version=\"3.0\"/><object class=\"G"
  "tkListStore\" id=\"listStore1\"><columns><!-- column-name accel "
  "--><column type=\"gchararray\"/><!-- column-name script_name -->"
  "<column type=\"gchararray\"/></columns></object><object class=\""
  "GtkWindow\" id=\"window\"><property name=\"width_request\">428</"
  "property><property name=\"height_request\">403</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"title\" translatable=\"yes\">Na"
  "utilusAccelsManager</property><property name=\"resizable\">False"
  "</property><property name=\"default_width\">500</property><prope"
  "rty name=\"default_height\">400</property><signal handler=\"on_w"
  "indow_destroy\" name=\"destroy\" swapped=\"no\"/><signal handler"
  "=\"on_main_window_show\" name=\"show\" object=\"listStore1\" swa"
  "pped=\"no\"/><child><object class=\"GtkFixed\" id=\"fixed1\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><child><object class=\"GtkTreeView\" id=\"tr"
  "eeview1\"><property name=\"width_request\">309</property><proper"
  "ty name=\"height_request\">375</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><"
  "property name=\"model\">listStore1</property><property name=\"en"
  "able_search\">False</property><property name=\"search_column\">0"
  "</property><child internal-child=\"selection\"><object class=\"G"
  "tkTreeSelection\" id=\"treeview-selection3\"/></child><child><ob"
  "ject class=\"GtkTreeViewColumn\" id=\"treeviewcolumn1\"><propert"
  "y name=\"title\" translatable=\"yes\">Accel</property><child><ob"
  "ject class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><at"
  "tributes><attribute name=\"text\">0</attribute></attributes></ch"
  "ild></object></child><child><object class=\"GtkTreeViewColumn\" "
  "id=\"treeviewcolumn2\"><property name=\"title\" translatable=\"y"
  "es\">Script Name</property><child><object class=\"GtkCellRendere"
  "rText\" id=\"cellrenderertext2\"/><attributes><attribute name=\""
  "text\">1</attribute></attributes></child></object></child></obje"
  "ct><packing><property name=\"x\">17</property><property name=\"y"
  "\">17</property></packing></child><child><object class=\"GtkButt"
  "on\" id=\"btnNew\"><property name=\"label\" translatable=\"yes\""
  ">New</property><property name=\"width_request\">83</property><pr"
  "operty name=\"height_request\">34</property><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"receives_default\">True</property><property n"
  "ame=\"resize_mode\">immediate</property><signal handler=\"on_btn"
  "New_clicked\" name=\"clicked\" swapped=\"no\"/></object><packing"
  "><property name=\"x\">336</property><property name=\"y\">19</pro"
  "perty></packing></child><child><object class=\"GtkButton\" id=\""
  "btnDelete\"><property name=\"label\" translatable=\"yes\">Delete"
  "</property><property name=\"width_request\">83</property><proper"
  "ty name=\"height_request\">34</property><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">True</property><property name="
  "\"resize_mode\">immediate</property><signal handler=\"on_btnDele"
  "te_clicked\" name=\"clicked\" object=\"treeview1\" swapped=\"no\""
  "/></object><packing><property name=\"x\">336</property><property"
  " name=\"y\">62</property></packing></child><child><object class="
  "\"GtkButton\" id=\"button4\"><property name=\"label\" translatab"
  "le=\"yes\">Cancel</property><property name=\"width_request\">83<"
  "/property><property name=\"height_request\">34</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"receives_default\">True</propert"
  "y><property name=\"resize_mode\">immediate</property><signal han"
  "dler=\"on_window_destroy\" name=\"clicked\" swapped=\"no\"/></ob"
  "ject><packing><property name=\"x\">336</property><property name="
  "\"y\">352</property></packing></child><child><object class=\"Gtk"
  "Button\" id=\"btnSave\"><property name=\"label\" translatable=\""
  "yes\">Save</property><property name=\"name\">83</property><prope"
  "rty name=\"width_request\">83</property><property name=\"height_"
  "request\">34</property><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">True</property><property name=\"resize_mode\">i"
  "mmediate</property><signal handler=\"on_btnSave_clicked\" name=\""
  "clicked\" swapped=\"no\"/></object><packing><property name=\"x\""
  ">335</property><property name=\"y\">309</property></packing></ch"
  "ild></object></child></object></interface>"
};
