static const char selectScriptDialogString [] = 
{
  "<?xml version=\"1.0\" ?><!-- Generated with glade 3.18.3 --><int"
  "erface><requires lib=\"gtk+\" version=\"3.12\"/><object class=\""
  "GtkListStore\" id=\"liststore1\"><columns><!-- column-name accel"
  " --><column type=\"gchararray\"/><!-- column-name script_name --"
  "><column type=\"gchararray\"/></columns></object><object class=\""
  "GtkDialog\" id=\"dialogSelectScript\"><property name=\"can_focus"
  "\">False</property><property name=\"type_hint\">dialog</property"
  "><signal handler=\"on_select_dialog_show\" name=\"show\" object="
  "\"liststore1\" swapped=\"no\"/><child internal-child=\"vbox\"><o"
  "bject class=\"GtkBox\" id=\"dialog-vbox1\"><property name=\"can_"
  "focus\">False</property><property name=\"orientation\">vertical<"
  "/property><property name=\"spacing\">2</property><child internal"
  "-child=\"action_area\"><object class=\"GtkButtonBox\" id=\"dialo"
  "g-action_area1\"><property name=\"can_focus\">False</property><p"
  "roperty name=\"layout_style\">end</property><child><object class"
  "=\"GtkBox\" id=\"box1\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\""
  "orientation\">vertical</property><child><object class=\"GtkButto"
  "n\" id=\"btnCancel\"><property name=\"label\" translatable=\"yes"
  "\">Cancel</property><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">True</property><property name=\"yalign\">0.5500000"
  "1192092896</property><signal handler=\"on_btnCancel_clicked\" na"
  "me=\"clicked\" object=\"dialogSelectScript\" swapped=\"no\"/></o"
  "bject><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">0</p"
  "roperty></packing></child></object><packing><property name=\"exp"
  "and\">True</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkBox\" id=\"box2\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"orientation\">vertical</property><child><object class="
  "\"GtkButton\" id=\"btnSelect\"><property name=\"label\" translat"
  "able=\"yes\">Select</property><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property na"
  "me=\"receives_default\">True</property><property name=\"yalign\""
  ">0.55000001192092896</property><signal handler=\"on_btnSelect_cl"
  "icked\" name=\"clicked\" object=\"cmbScriptNames\" swapped=\"no\""
  "/></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\""
  ">0</property></packing></child></object><packing><property name="
  "\"expand\">True</property><property name=\"fill\">True</property"
  "><property name=\"position\">1</property></packing></child></obj"
  "ect><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">False</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkBox\" id=\"bo"
  "x3\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"orientation\">verti"
  "cal</property><child><object class=\"GtkComboBox\" id=\"cmbScrip"
  "tNames\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"model\">liststo"
  "re1</property><property name=\"active\">1</property><property na"
  "me=\"id_column\">1</property><child><object class=\"GtkCellRende"
  "rerText\" id=\"cellScriptName\"/><attributes><attribute name=\"t"
  "ext\">1</attribute></attributes></child></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">True"
  "</property><property name=\"position\">0</property></packing></c"
  "hild></object><packing><property name=\"expand\">True</property>"
  "<property name=\"fill\">True</property><property name=\"padding\""
  ">1</property><property name=\"position\">1</property></packing><"
  "/child></object></child></object></interface>"
};
